ALTER TABLE games ADD COLUMN total_rounds INT NOT NULL DEFAULT 3;
ALTER TABLE games ADD COLUMN team_size INT NOT NULL DEFAULT 5;
ALTER TABLE games ADD COLUMN current_multiplier INT NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN controlling_team INT DEFAULT NULL;

ALTER TABLE participants ADD COLUMN member_order INT NOT NULL DEFAULT 0;
